### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rcrowe** [rcrowe/TwigBridge#134]
My plan for 0.7:
- [ ] Work on better test coverage
- [ ] Implement acceptance/functional tests that use TwigBridge with Laravel (artisan serve)
- [ ] Have enjoyed using Codeception. Maybe move over to using.
