### ISSUE TITLE
Version 0.6.0

### ISSUE THREAD

**Issue by rcrowe** [rcrowe/TwigBridge#62]
TwigBridge has grown and become more important while at the same time I've grown unhappy with how some parts of the library and hope to fix this with the next release.

So lets open things for discussion and get the ball rolling.
- [x] Improve the Twig syntax for calling aliases (#61)
- [x] Improve template loading (#39, #60)
- [ ] Actually get the twig:compile working (#41)
- [x] Make better use of the IoC (#56)
- [x] Improve Laravel composer / creator support (#59, #66)
- [ ] Improve tests & coverage
- [x] Review getAttributes [function](https://github.com/rcrowe/TwigBridge/blob/master/src/TwigBridge/Twig/Template.php#L51)
- [ ] Improved package support (#74)
- [x] Render string templates (#94)
- [ ] Decide which functions / filters are escaped by Laravel extensions

@barryvdh @ivannpaz
